/*========TOPIC CATEGORIES========*/
const MENTAL_MODELS = { name: "Mental Models", route: "/essays/mentalmodels" };
const EVOLUTION = { name: "Evolution", route: "/essays/evolution" };

/*========CONTENT CATEGORIES========*/
const PARAGRAPH = "Paragraph";
const QUOTE = "Quote";
const IMAGE = "Image";

const EssayList = [
    { // start of Replicators Essay
        id: 1,
        title: "Replicators",
        sources: [
            { 
                title: "The Selfish Gene by Richard Dawkins",
                link: "https://www.amazon.com/Selfish-Gene-Anniversary-Landmark-Science/dp/0198788606/ref=sr_1_1?keywords=the+selfish+gene&qid=1571264148&sr=8-1"
            }
        ],
        categories: [ MENTAL_MODELS, EVOLUTION ],
        essay: [
            {
                type: PARAGRAPH,
                content: "Darwin’s 'survival of the fittest' is really a special case of a more general law of 'survival of the stable'.  The universe is populated by stable things.  A stable thing is a collection of atoms that is permanent enough or common enough to deserve a name.  The things that we see around us, and which we think of as needing explanation—rocks, galaxies, ocean waves, rain drops—are all, to a greater or lesser extent, stable patterns of atoms.  The point that is relevant here is that, before the coming of life on earth, some rudimentary evolution of molecules could have occurred by ordinary processes of physics and chemistry.  There is no need to think of design or purpose or directedness.  If a group of atoms in the presence of energy falls into a stable pattern, it will tend to stay that way.  The earliest form of natural selection was simply a selection of stable forms and a rejection of unstable ones. There is no mystery about this.  It had to happen by definition."
            },
            {
                type: PARAGRAPH,
                content: "From this, of course, it does not follow that you can explain the existence of entities as complex as human beings by exactly the same principles on their own.  It is no good taking the right number of atoms and shaking them together with some external energy until they happen to fall into the right pattern, and out drops Adam!  This is where Darwin’s theory, in its most general form, comes to the rescue."
            },
            {
                type: PARAGRAPH,
                content: "We do not know what chemical raw materials were abundant on earth before the coming of life, but among the plausible possibilities are water, carbon dioxide, methane, and ammonia: all simple compounds known to be present on at least some of the other planets in our solar system.  Chemists have tried to imitate the chemical conditions of the young earth.  They have put these simple substances in a flask and supplied a source of energy such as ultraviolet light or electric sparks—an artificial simulation of primordial lightning.  After a few weeks of this, something interesting is usually found inside the flask: a weak brown soup containing a large number of molecules more complex than the ones originally put in.  In particular, amino acids have been found—the building blocks of proteins, one of the two great classes of biological molecules.  More recently, laboratory simulations of the chemical conditions of earth before the coming of life have yielded organic substances called purines and pyrimidines.  These are building blocks of the genetic molecule—DNA itself."
            },
            {
                type: PARAGRAPH,
                content: "Processes analogous to these must have given rise to the ‘primeval soup’ which biologists and chemists believe constituted the seas some three to four thousand million years ago.  The organic substances became locally concentrated (perhaps in drying scum round the shores), and under the further influence of energy such as ultraviolet light from the sun, they combined into larger molecules.  At some point, a particularly remarkable molecule was formed by accident.  We will call it the replicator.  It had the extraordinary property of being able to create copies of itself.  Suddenly, a new kind of ‘stability’ came into the world.  Previously it is probable that no particular kind of complex molecule was very abundant in the soup, because each was dependent on building blocks happening to fall by luck into a particular stable configuration.  As soon as the replicator was born it must have spread its copies rapidly throughout the seas."
            },
            {
                type: PARAGRAPH,
                content: "So we seem to arrive at a large population of identical replicas.  But now we must mention an important property of any copying process: it is not perfect.  Mistakes will happen.  Erratic copying in biological replicators can in a real sense give rise to improvement, and it was essential for the progressive evolution of life that some errors were made.  As mis-copyings were made and propagated, the primeval soup became filled by a population not of identical replicas, but of several varieties of replicating molecules, all ‘descended’ from the same ancestor.  Would some varieties have been more numerous than others? Almost certainly yes.  Some varieties would have been inherently more stable than others.  Certain molecules once formed would be less likely than others to break up again.  These types would become relatively  numerous in the soup, not only as a direct logical consequence of their ‘longevity,’ but also because they would have a long time available for making copies of themselves.  Replicators of high longevity would therefore tend to become more numerous and, other things being equal, there would have been an ‘evolutionary trend’ towards greater longevity in the population of molecules."
            },
            {
                type: PARAGRAPH,
                content: "But other things were probably not equal, and another property of a replicator variety that must have had even more importance in spreading it through the population was speed of replication or ‘fecundity’.  If replicator molecules of type A make copies of themselves on average once a week while those of type B make copies of themselves once an hour, it is not difficult to see that pretty soon type A molecules are going to be far outnumbered, even if they ‘live’ much longer than B molecules.  There would therefore probably have been an ‘evolutionary trend’ towards higher ‘fecundity’ of molecules in the soup.  A third characteristic of replicator molecules which would have been positively selected is accuracy of replication.  If molecules of type X and type Y last the same length of time and replicate at the same rate, but X makes a mistake on average every tenth replication while Y makes a mistake only every hundredth replication, Y will obviously become more numerous."
            },
            {
                type: PARAGRAPH,
                content: "Thus, the primeval soup must have become populated by stable varieties of molecule; stable in that either the individual molecules lasted a long time, or they replicated rapidly, or they replicated accurately.  Evolutionary trends toward these three kinds of stability are essentially what a biologist means by evolution when he is speaking of the mechanism of natural selection in living creatures."
            },
            {
                type: PARAGRAPH,
                content: "The next important link in the argument—one that Darwin himself laid stress on (although he was talking about animals and plants, not molecules)—is competition.  The primeval soup was not capable of supporting an infinite number of replicator molecules.  In our picture of the replicator acting as a template or mold, we supposed it to be bathed in a soup rich in the small building block molecules necessary to make copies.  But when the replicators became numerous, building blocks must have been used up at such a rate that they became a scarce and precious resource.  Different varieties or strains of replicator must have competed for them, and less-favored varieties must actually have become less numerous because of competition.  There was a struggle for existence among replicator varieties.  Ways of increasing stability and of decreasing rivals’ stability became more elaborate and more efficient.  Some of them may even have ‘discovered’ how to break up molecules of rival varieties chemically and use the building blocks released for making their own copies.  These proto-carnivores simultaneously obtained food and removed competing rivals.  Other replicators perhaps discovered how to protect themselves, either chemically, or by building a physical wall of protein around themselves.  This may have been how the first living cells appeared.  Replicators began not merely to exist, but to construct for themselves containers—vehicles for their continued existence.  The replicators that survived were the ones that built ‘survival machines’ for themselves to live in.  The first survival machines probably consisted of nothing more than a protective coat.  But making a living got steadily harder as new rivals arose with better and more effective survival machines.  Survival machines got bigger and more elaborate, and the process was cumulative and progressive."
            },
            {
                type: PARAGRAPH,
                content: "These replicators are in you and in me; they created us, body and mind; and their preservation is the ultimate rationale for our existence.  They have come a long way, those replicators.  Now they go by the name of genes, and we are their survival machines.  ‘We’ does not mean just people.  It embraces all animals, plants, bacteria, and viruses.  Different sorts of survival machine appear very varied on the outside and in their internal organs.  Yet in their fundamental chemistry they are rather uniform, and, in particular, the replicators that they bear, the genes, are basically the same kind of molecule in all of us—from bacteria to elephants.  We are all survival machines for the same kind of replicator—molecules called DNA."
            },
            {
                type: PARAGRAPH,
                content: "The original replicators (in the primeval soup) may have been a related kind of molecule to DNA, or they may have been totally different.  Nonetheless, DNA is in undisputed charge today.  A DNA molecule is a long chain of building blocks, small molecules called nucleotides.  Just as protein molecules are chains of amino acids, so DNA molecules are chains of nucleotides.  It consists of a pair of nucleotide chains twisted together in an elegant spiral; the ‘double helix’; the ‘immortal coil’.   The nucleotide building blocks come in only four different kinds (whose names may be shortened to A, T, C, and G).  These are the same in all animals and plants.  What differs is the order in which they are strung together.  A G building block from a man is identical in every particular to a G building block from a snail.  But the sequence of building blocks in a man is not only different from that in a snail.  It is also different—though less so—from the sequence in every other man (except in the special case of identical twins)."
            },
            {
                type: PARAGRAPH,
                content: "Our DNA lives inside our bodies.  It is not concentrated in a particular part of the body, but is distributed among the cells.  Every cell contains a complete copy of that body’s DNA. This DNA can be regarded as a set of instructions for how to make a body, written in the A, T, C, G alphabet of the nucleotides.  It is as though, in every room of a gigantic building, there was a book-case containing the architect’s plans for the entire building.  The ‘book-case’ in a cell is called the nucleus.  The architect’s plans run to 46 volumes in man—the number is different in other species.  The ‘volumes’ are called chromosomes.  The ‘pages’ are called genes, although the division between genes is less clear-cut than the division between the pages of a book.  Incidentally, there is of course no ‘architect’.  The DNA instructions have been assembled by natural selection."
            },
            {
                type: PARAGRAPH,
                content: "DNA molecules do two important things.  Firstly, they replicate, that is to say they make copies of themselves.  This has gone on non-stop ever since the beginning of life, and the DNA molecules are now very good at it indeed.  As an adult, you consist of a thousand million million cells, but when you were first conceived you were just a single cell, endowed with one master copy of the architect’s plans.  This cell divided into two, and each of the two cells received its own copy of the plans.  Successive divisions took the number of cells up to 4, 8, 16, 32 and so on into the billions.  At every division the DNA plans were faithfully copied, with scarcely any mistakes."
            },
            {
                type: PARAGRAPH,
                content: "The second important thing DNA does is that it indirectly supervises the manufacture of a different kind of molecule—protein.  Proteins not only constitute much of the physical fabric of the body; they also exert sensitive control over all the chemical processes inside the cell.  Exactly how this eventually leads to the development of a baby will take a long time to explain, but it is a fact that it does.  The evolutionary importance of the fact that genes control embryonic development is this: it means that genes are at least partly responsible for their own survival in the future, because their survival depends on the efficiency of the bodies in which they live and which they help to build.  This means that any one individual body is just a temporary vehicle for a short-lived combination of genes.  The combination of genes that is any one individual may be short-lived, but the genes themselves are potentially very long-lived.  One gene may be regarded as a unit that survives through a large number of successive individual bodies."
            },
            {
                type: PARAGRAPH,
                content: "Previously we said that the plans for building a human body are spelt out in 46 volumes.  This was an over-simplification.  The 46 chromosomes consist of 23 pairs of chromosomes.  In the nucleus of every cell are two alternative sets of 23 volumes of plans.  Call them Volume 1A and Volume 1B, Volume 2A and Volume 2B, etc., down to Volume 23A and Volume 23B.  We receive each chromosome intact from one of our two parents.  Volumes 1A, 2A, 3A, … came, say, from the father.  Volumes 1B, 2B, 3B, came from the mother.  It is very difficult in practice, but in theory you could look with a microscope at the 46 chromosomes in any one of your cells, and pick out the 23 that came from your father and the 23 that came from your mother.  While theoretically possible, this kind of gross, whole-chromosome distribution does not happen.  The truth is rather more complex.  What happens is that single pages, or rather multi-page chunks, are detached and swapped with the corresponding chunks from the alternative volume.  Therefore every sperm cell made by an individual is unique, even though all his sperms assembled their 23 chromosomes from bits of the same set of 46 chromosomes.  Eggs are made in a similar way in ovaries, and they too are all unique.  During the manufacture of a sperm (or egg), bits of each paternal chromosome physically detach themselves and change place with exactly corresponding bits of maternal chromosome.  The process of swapping bits of chromosome is called crossing over—it means that if you got out your microscope and looked at the chromosomes in one of your own sperms (or eggs if you are female) it would be a waste of time trying to identify chromosomes that originally came from your father and chromosomes that originally came from your mother.  Any one chromosome in a sperm would be a patchwork, a mosaic of maternal genes and paternal genes."
            },
            {
                type: PARAGRAPH,
                content: "A gene is defined as any portion of chromosomal material that potentially lasts for enough generations to serve as a unit of natural selection.  It is a replicator with high copying-fidelity.  Copying-fidelity is another way of saying longevity-in-the-form-of-copies.  The gene is the fundamental unit of natural selection.  Natural selection in its most general form means the differential survival of entities.  Some entities live and others die but, in order for this selective death to have any impact on the world, an additional condition must be met.  Each entity must exist in the form of lots of copies, at least some of the entities must be potentially capable of surviving—in the form of copies—for a significant period of evolutionary time.  Small genetic units have these properties.  Individuals, groups, and species do not."
            },
            {
                type: PARAGRAPH,
                content: "It is its potential immortality that makes a gene a good candidate as the basic unit of natural selection.  However, many new genes do not even make it past their first generation.  The few new ones that succeed do so partly because they are lucky, but mainly because they are good at making survival machines.  They have an effect on the embryonic development of each successive body in which they find themselves, such that the body is a little bit more likely to live and reproduce than it would have been under the influence of a rival gene.  Genes are competing directly with their rivals for survival.  Any gene that behaves in such a way as to increase its own survival chances in the gene pool at the expense of its rivals will, by definition, tend to survive.  Whenever we are trying to explain the evolution of some characteristic (i.e. altruistic behavior), we should simply ask ourselves: what effect will this characteristic have on frequencies of genes in the gene pool?  Evolution is the process by which some genes become more numerous and others less numerous in the gene pool."
            },
            {
                type: PARAGRAPH,
                content: "If there is any principle that is true of all life, it is that all life evolves by the differential survival of replicating entities.  For more than three thousand million years, the gene was the only replicating entity worth talking about in the world.  Biologists have assimilated the idea of genetic evolution so deeply that we tend to forget that it is only one of the many possible kinds of evolution.  However, Darwinism is too big a theory to be confined to the narrow context of the gene.  Genes are special because they are replicators, but human culture is a new kind of replicator that has emerged on this planet."
            },
            {
                type: PARAGRAPH,
                content: "Most of what is unusual about man can be summed up in one word: culture.  Cultural transmission is analogous to genetic transmission in that it can give rise to a form of evolution.  Richard Dawkins uses the word meme (abbreviation of “mimeme”) as a name for the new replicator.  A meme is a unit of cultural transmission or a unit of imitation.  Examples of memes are tunes, ideas, catch-phrases, clothes fashions, ways of making pots or building arches.  Just as genes propagate themselves in the gene pool by leaping form body to body via sperms or eggs, so memes propagate themselves in the meme pool by leaping from brain to brain via a process which, in the broad sense, can be called imitation.  If a scientist hears, or reads about, a good idea, he passes it on to his colleagues and students.  He mentions it in his articles and his lectures.  If the idea catches on, it can be said to propagate itself, spreading from brain to brain.  Memes should be regarded as living structures, not just metaphorically but technically.  When you plant a fertile meme in my mind, you literally parasitize my brain, turning it into a vehicle for the meme’s propagation in just the way that a virus may parasitize the genetic mechanism of a host cell."
            },
            {
                type: PARAGRAPH,
                content: "Imitation, in a broad sense, is how memes can replicate.  But just as all genes that can replicate don’t do so successfully, so some memes are more successful in the meme pool than others.  This is the analogue of natural selection.  Recall, there are three qualities that make for high survival value among replicators: longevity, fecundity, and copying fidelity."
            },
            {
                type: PARAGRAPH,
                content: "A gene was defined as a length of chromosome with just sufficient for copying fidelity to serve as a viable unit of natural selection.  An ‘idea-meme’ might be defined as an entity that is capable of being transmitted from one brain to another.  If a single phrase of Beethoven’s ninth symphony is sufficiently distinctive and memorable to be abstracted from the context of the whole symphony, and transmitted from one person to another, then to that extent it deserves to be called one meme."
            },
            {
                type: PARAGRAPH,
                content: "The human brain, and the body that it controls, cannot do more than one or a few things at once.  If a meme is to dominate the attention of a human brain, it must do so at the expense of ‘rival’ memes.  Other commodities for which memes compete are radio and television time, billboard space, newspaper columns, and library shelf-space.  Selection favors memes that exploit their cultural environment to their own advantage.  The cultural environment consists of other memes which are also being selected.  The meme pool therefore comes to have the attributes of an evolutionary stable set, which new memes find hard to invade."
            },
            {
                type: PARAGRAPH,
                content: "When we die, there are two things we can leave behind us: genes and memes.  We were built as gene machines, created to pass on our genes.  But as each generation passes, the contribution of your genes is halved.  It does not take long to reach negligible proportions.  Our genes may be immortal but the collection of genes that is any one of us is bound to crumble away.  However, if you contribute to the world’s culture, if you have a good idea, compose a tune, invent a sparking plug, write a poem, it may live on, intact, long after your genes have dissolved in the common pool.  Socrates may or may not have a gene or two alive in the world today, but who cares?  The meme-complexes of Socrates, Leonardo, Copernicus, and Marconi are still going strong."
            },
            {
                type: PARAGRAPH,
                content: "One unique feature of man is his capacity for conscious foresight.  Genes and memes have no foresight.  They are unconscious, blind, replicators.  The fact that they replicate, together with certain further conditions, means that they will tend towards the evolution of qualities which can be called selfish (i.e. behaving in such a way as to increase their numbers in future gene or meme pools).  Even if we assume that individual man is fundamentally selfish, our conscious foresight—our capacity to simulate the future in imagination—could save us from the worst selfish excesses of the blind replicators.  We have the power to defy the selfish genes of our birth and, if necessary, the selfish memes of our indoctrination.  We can even discuss ways of deliberately cultivating and nurturing pure, disinterested altruism—something that has no place in nature, something that has never existed before in the whole history of the world.  We are built as gene machines and cultured as meme machines, but we have the power to turn against our creators.  We, alone on earth, can rebel against the tyranny of the selfish replicators."
            },
            {
                type: PARAGRAPH,
                content: "In summary, the fundamental unit, the prime mover of all life, is the replicator.  A replicator is anything in the universe of which copies are made.  Replicators come into existence, in the first place, by chance, by the random jostling of smaller particles.  Once a replicator has come into existence, it is capable of generating an indefinitely large set of copies of itself.  No copying process is perfect, however, and the population of replicators comes to include varieties that differ from one another.  Some of these varieties turn out to have lost the power of self-replication, and their kind ceases to exist when they themselves cease to exist.  Others can still replicate but less effectively.  Yet other varieties happen to find themselves in possession of new tricks: they turn out to be even better self-replicators than their predecessors and contemporaries.  It is their descendants that come to dominate the population.  As time goes by, the world becomes filled with the most powerful and ingenious replicators."
            }
        ]
    } // End of Replicators essay (ID: 1)
]

export default EssayList;